[package]
name = "web-url"
version = "0.11.0"
description = "This library aids in processing web-based URLs."
readme = "README.md"
repository = "https://github.com/nikdeapen/web-url"
homepage = "https://github.com/nikdeapen/web-url"
authors = ["Nik Deapen <nik@deapen.com>"]
edition = "2024"
rust-version = "1.88"
license = "MIT"
keywords = ["url", "web", "parse", "normalization"]
categories = ["parser-implementations", "web-programming"]

[dependencies]
address = "0.21.0"

[lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"

[lints.clippy]
copy_iterator = "warn"
module_inception = "allow"
must_use_candidate = "warn"
